export const PLANTS_DATA = [
    {
        id: '1',
        name: 'Kentang Granola',
        latin: 'Solanum tuberosum',
        description: 'Kentang jenis ini sangat populer untuk keripik. Membutuhkan tanah gembur dan penyinaran matahari penuh. Masa panen sekitar 90-100 hari.',
        image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800',
        difficulty: 'Sedang',
        growthTime: '90 Hari',
        totalXp: 1350,
        progress: 45,
        color: '#059669',
        tasks: [
            { id: '1-1', title: 'Persiapan Lahan', xp: 100, status: 'completed', desc: 'Gemburkan tanah dan campur pupuk kandang.' },
            { id: '1-2', title: 'Pilih Bibit Unggul', xp: 150, status: 'completed', desc: 'Pastikan bibit memiliki mata tunas yang sehat.' },
            { id: '1-3', title: 'Penanaman Awal', xp: 200, status: 'active', desc: 'Tanam bibit sedalam 5-7 cm.' },
            { id: '1-4', title: 'Penyiraman Rutin', xp: 100, status: 'locked', desc: 'Siram pagi dan sore hari.' },
            { id: '1-5', title: 'Pupuk Susulan', xp: 300, status: 'locked', desc: 'Berikan NPK saat usia 3 minggu.' },
            { id: '1-6', title: 'Panen Raya', xp: 500, status: 'locked', desc: 'Gali umbi saat daun mulai menguning.' },
        ]
    },
    {
        id: '2',
        name: 'Tomat Cherry',
        latin: 'Solanum lycopersicum var. cerasiforme',
        description: 'Tomat mungil yang manis dan segar. Cocok untuk salad atau camilan sehat. Membutuhkan penyangga saat tumbuh.',
        image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?q=80&w=800',
        difficulty: 'Mudah',
        growthTime: '60-70 Hari',
        totalXp: 1000,
        progress: 10,
        color: '#EA580C',
        tasks: [
            { id: '2-1', title: 'Semai Benih', xp: 100, status: 'active', desc: 'Semai benih di tray semai hingga berkecambah.' },
            { id: '2-2', title: 'Pindah Tanam', xp: 150, status: 'locked', desc: 'Pindahkan ke pot besar saat muncul 4 daun sejati.' },
            { id: '2-3', title: 'Pasang Ajir', xp: 100, status: 'locked', desc: 'Pasang tongkat penyangga agar tanaman tegak.' },
            { id: '2-4', title: 'Pemupukan Rutin', xp: 250, status: 'locked', desc: 'Berikan pupuk NPK setiap 2 minggu sekali.' },
            { id: '2-5', title: 'Panen', xp: 400, status: 'locked', desc: 'Petik buah tomat yang sudah merah merona.' },
        ]
    },
    {
        id: '3',
        name: 'Cabai Rawit',
        latin: 'Capsicum frutescens',
        description: 'Si kecil yang pedas! Tanaman wajib bagi pecinta sambal. Tahan panas dan mudah tumbuh di pot.',
        image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?q=80&w=800',
        difficulty: 'Mudah',
        growthTime: '80-90 Hari',
        totalXp: 1100,
        progress: 25,
        color: '#DC2626',
        tasks: [
            { id: '3-1', title: 'Jemur Benih', xp: 50, status: 'completed', desc: 'Jemur biji cabai kering sebelum disemai.' },
            { id: '3-2', title: 'Penyemaian', xp: 100, status: 'active', desc: 'Tanam di media tanam halus.' },
            { id: '3-3', title: 'Pindah Tanam', xp: 150, status: 'locked', desc: 'Pindahkan bibit ke pot yang lebih besar setelah tumbuh 4-5 daun.' },
            { id: '3-4', title: 'Pemupukan', xp: 300, status: 'locked', desc: 'Berikan pupuk kandang atau NPK agar berbuah lebat.' },
            { id: '3-5', title: 'Panen', xp: 500, status: 'locked', desc: 'Panen cabai saat warnanya sudah merah cerah.' },
        ]
    },
    {
        id: '4',
        name: 'Sawi Hijau',
        latin: 'Brassica rapa var. parachinensis',
        description: 'Sayuran hijau yang kaya serat dan vitamin. Sangat cepat panen, cocok untuk pemula yang ingin hasil instan.',
        image: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?q=80&w=800',
        difficulty: 'Sangat Mudah',
        growthTime: '30-40 Hari',
        totalXp: 800,
        progress: 10,
        color: '#65A30D',
        tasks: [
            { id: '4-1', title: 'Tabur Benih', xp: 100, status: 'active', desc: 'Tabur benih secara merata di bedengan.' },
            { id: '4-2', title: 'Penjarangan', xp: 100, status: 'locked', desc: 'Cabut bibit yang terlalu rapat.' },
            { id: '4-3', title: 'Penyiraman', xp: 100, status: 'locked', desc: 'Jaga kelembaban tanah dengan menyiram rutin.' },
            { id: '4-4', title: 'Pemupukan Daun', xp: 200, status: 'locked', desc: 'Semprot pupuk daun agar daun lebar dan hijau.' },
            { id: '4-5', title: 'Panen', xp: 300, status: 'locked', desc: 'Potong pangkal batang saat daun sudah lebar.' },
        ]
    },
    {
        id: '5',
        name: 'Kangkung',
        latin: 'Ipomoea aquatica',
        description: 'Sayuran daun yang sangat populer dan tumbuh cepat. Bisa dipanen dalam waktu singkat.',
        image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=800&auto=format&fit=crop',
        difficulty: 'Sangat Mudah',
        growthTime: '21-25 Hari',
        totalXp: 900,
        progress: 10,
        color: '#10B981',
        tasks: [
            { id: '5-1', title: 'Siapkan Benih', xp: 100, status: 'active', desc: 'Rendam benih kangkung dalam air hangat selama 1 jam.' },
            { id: '5-2', title: 'Tebar Benih', xp: 100, status: 'locked', desc: 'Tebar benih di media tanam yang lembab.' },
            { id: '5-3', title: 'Penyiraman Rutin', xp: 100, status: 'locked', desc: 'Siram pagi dan sore agar tanah tetap lembab.' },
            { id: '5-4', title: 'Pemupukan', xp: 200, status: 'locked', desc: 'Berikan pupuk urea atau NPK daun.' },
            { id: '5-5', title: 'Panen', xp: 400, status: 'locked', desc: 'Potong batang kangkung, sisakan sedikit untuk tumbuh lagi.' },
        ]
    }
];
